config/routes.rb
A98lumens::Application.routes.draw do
  devise_for :users

  ActiveAdmin.routes(self)

  root :to => "static_pages#home"

  match 'sandbox', :to=> "users#sandbox", :as => "sandbox"
  match 'about', :to=> "static_pages#about", :as => "about"
  match 'contact', :to=> "static_pages#contact", :as => "contact"
  match 'projects', :to=> "static_pages#projects", :as => "projects"
  match 'get/state_retail_price', :to => "static_pages#state_retail_price", :as => "state_retail_price"
  match 'test', :to=> "static_pages#test", :as => "test"
  match 'learn', :to=> "static_pages#learn", :as => "learn"
  match 'faqs', :to=> "static_pages#faqs", :as => "faqs"
  match 'consult', :to=> "static_pages#consult", :as => "consult"
  match 'pricing', :to=> "static_pages#pricing", :as => "pricing"
  match 'reserve', :to=> "static_pages#reserve", :as => "reserve"
  match 'benefits', :to=> "static_pages#benefits", :as => "benefits"
  match 'submit_reserve', :to=> "static_pages#submit_reserve", :as => "submit_reserve"
  match 'info_mail', :to=> "static_pages#info_mail", :as => "info_mail"
  match 'calculator', :to=> "static_pages#calculator", :as => "calculator"
  match 'data/state_retail_price', :to => "static_pages#state_retail_price", :as => "state_retail_price"

  resources :energy_data

  resources :users

  match '/users/edit', :to => "devise/registrations#edit", :as => "edit_user_registration"
  match '/users/new', :to => "devise/registrations#new", :as => "new_user_registration"
  match 'get/user_data', :to => "users#user_inst_data", :as => "user_inst_data"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  email                  :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  superadmin             :boolean          default(FALSE), not null
#  Location               :string(255)
#  panel_zip              :string(255)
#  state_id               :integer
#

class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, 
         :rememberable, :trackable, :validatable
  attr_accessible :name, :email, :password, :location, :password_confirmation, 
                  :remember_me, :created_at, :panel_zip
  has_many :panels, :foreign_key => "user_id"

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:new, :create, :user_inst_data, :sandbox]

  # test new dashboard functionality with sample profile
  def sandbox
    @user = User.find(1)

    if defined? params[:energy_data][:panel_id]
      select_option = params[:energy_data][:panel_id]
    else
      select_option = 0
    end

    if (select_option.to_i<1 || select_option.nil?)  # best way to check if a variable is undefined?
      puts 'first condition'
      @panel = @user.panels.where(:panel_num=>1).first
    else
      @panel = @user.panels.where(:panel_num=>params[:energy_data][:panel_id]).first
    end

    client = Weatherman::Client.new

    @potential_trees = (463000*0.00069)*0.08 - @panel.calculate_overall_trees_for;
    @potential_cars = (463000*0.00069)/4200 - @panel.calculate_overall_cars_for;

    if !@user.panel_zip.nil?
      response = client.lookup_by_woeid(lookup_woeid(@user.panel_zip))

      @weather = response.description
      @latitude = response.latitude
      @longitude = response.longitude
      @weather = clean_forecast(@weather).html_safe
      city = response.location['city']
      state = response.location['region']
      @location = [city, state].join(',')
    end

    if @panel.energy_data.first.nil?
      puts "pass"
    else
      puts "dayTotal"
      @dayTotals = @panel.consolidate_day
      puts "weekTotal"
      @days, @weekTotals = @panel.consolidate_week
      puts "yearTotal"
      @monthTotals = @panel.monthSum
    end

    # gon variables
    gon.user = @user
    gon.dayTotals = @dayTotals
    gon.monthTotals = @monthTotals
    gon.weekTotals = @weekTotals
    gon.overall_power_for = @panel.calculate_overall_power_for
    gon.panel_id = @panel.panel_num
    gon.latitude = @latitude
    gon.longitude = @longitude

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    @this_user = User.find(1)

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

      client = Weatherman::Client.new

      if !@user.panel_zip.nil?
        response = client.lookup_by_woeid(lookup_woeid(@user.panel_zip))

        @weather = response.description
        @weather = clean_forecast(@weather).html_safe
        city = response.location['city']
        state = response.location['region']
        @location = [city, state].join(',')
     end

      puts @user.energy_data.nil?
      if @user.energy_data.first.nil?
        puts "pass"
      else
        @energy_data = @user.energy_data.order("created_at DESC").limit(10)
        @dayTotals = @user.consolidate_day
        @days, @weekTotals = @user.consolidate_week
        @monthTotals = @user.monthSum

        #totals
        @weekPowerTotal = @user.calculate_week_power_for
      end

      respond_to do |format|
        format.html # show.html.erb
        format.js
        format.json { render json: @user }
      end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Welcome to the 98Lumens family!' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  # present data to grab for view work
  # get/user_data
  def user_inst_data
    timestamp = params[:time_now]
    user_id = params[:user_id]
    panel_id = params[:panel_id]

    if (params[:index].to_i<1 || params[:index].nil?)  # best way to check if a variable is undefined?
      panel_id = 1
    else
      panel_id = params[:panel_id]
    end

    before = fetch_data_at_time(user_id, timestamp, panel_id)
    after = fetch_data_at_time(user_id, (timestamp.to_i+3600), panel_id)

    response = Hash.new

    response['before'] = before
    response['after'] = after

    render json: response.to_json
  end

  private
    def clean_forecast(forecast)
      forecast_sep = forecast.split("\n");
      new_forecast = forecast_sep[0..3].join()
    end

    def lookup_woeid(zip)
      woeid_cities = {"93706" => "2407517"}

      woeid_cities[zip].to_i
    end

    def current_user?(user)
      if current_user=user
        true
      else
        false
      end
    end

    def fetch_data_at_time(user_id, time_at, panel_id)
      # convert time to object
      timestamp = Time.zone.at(time_at.to_i)
      # break down timestamp right now
      year = timestamp.year
      month = timestamp.month
      day = timestamp.day
      hour = timestamp.hour+1 #we're 1-indexed

      # find data
      # HARDCODING PANEL #1 for test
      panel = Panel.where(:user_id=>user_id, :panel_num=>panel_id).first
      response = panel.energy_data.where(:year=>year, :month=>month, :day=>day, :hour=>hour).select('power')
      
      #response = response(:include=> :power)

      #@response_list = r

      return response
    end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_dash_content.html.erb
  <!-- chart and highlight row -->
<div class="row-fluid">
        <p>
          <div class="btn-group  pull-right" data-toggle="buttons-radio">
            <button type="button" class="btn" id="day">Today</button>
            <button type="button" class="btn" id="month" >Last 30 days</button>
            <button type="button" class="btn" id="year">This year</button>
          </div>
        <p>
</div>

<div class="row-fluid">
          <div class="span3">
            <div class="power-output">
              <div id='chart_div' style="padding-left:17px"></div>
              
              <div class='summary-banner'>
                  Lifetime output 
                  <div class="hover-question" title="Over th=e lifetime of your panel, it has produced the amount of energy below measured in kilowatt-hours, the most common measure of electricity in the United States." style="float:right">
                    <%= image_tag "question_mark.png", :size=>"13x13" %>
                  </div>
              </div>

              <div class="highlight-text power-read"></div>
              
              <div class='summary-banner'>
                  Lifetime earning 
                  <div class="hover-question" title="This is the total payback that your panel has produced since you bought it." style="float:right">
                    <%= image_tag "question_mark.png", :size=>"13x13" %>
                  </div>
              </div>

              <div class="highlight-text money-read"></div>

              <div class='summary-banner'>
                  Lifetime C02 offset
                  <div class="hover-question" title="By replacing dirty energy, you've prevented the production of carbon dioxide." style="float:right">
                    <%= image_tag "question_mark.png", :size=>"13x13" %>
                  </div>
              </div>

              <div class="highlight-text emissions-read"></div>

              <div class='summary-banner'>
                  Trees planted (<%=  number_to_human(@panel.calculate_overall_trees_for, :precision => 4) %>) 
                  <div class="hover-question" title="Trees capture approximately 12.5 kg of carbon dioxide per year. The transparent trees are projected." style="float:right">
                    <%= image_tag "question_mark.png", :size=>"13x13" %>
                  </div>
              </div>

              <div class="tree-count">
                <div class="highlight-text">
                  <% for i in 1..(@panel.calculate_overall_trees_for) %>
                    <%= image_tag "tree.png", :size=>"20x20" %>
                  <% end %>

                  <% for i in 1..(@potential_trees) %>
                    <span style="opacity:.2"><%= image_tag "tree.png", :size=>"20x20", :class=>"tree_potential" %></span>
                  <% end %>
                </div>
              </div>

              <div class='summary-banner'>
                  Cars taken off road (<%=  number_to_human(@panel.calculate_overall_cars_for, :precision => 2) %>) 
                  <div class="hover-question" style="float:right" title="Cars produce on average 4200 kg of carbon dioxide a year.">
                    <%= image_tag "question_mark.png", :size=>"13x13" %>
                  </div>
              </div>

              <div class="highlight-text">
                <% for i in 1..@panel.calculate_overall_cars_for %>
                  <%= image_tag "car.png", :size=>"20x20" %>
                <% end %>

                <% for i in 1..(@potential_cars) %>
                  <span style="opacity:.2"><%= image_tag "car.png", :size=>"20x20", :class=>"tree_potential" %></span>
                <% end %>
              </div>
              
            </div>
          </div>
          <div class="span9">
            <div id="year-graph" style="width:100%;height:550px;"></div>
          </div>
  </div>

<script type="text/javascript">
  $(document).ready($(function(){

      /*****************************************
      * Misc
      ******************************************/

      // divs that are tooltippable
      $('.hover-question').tooltip();

      // Twitter redirection
      var url = "http://www.98lumens.com"
      var todays_power = <%= @panel.last_day_power.to_json %>
      var text = "My%20solar%20panel%20generated%20"+ todays_power[1].toFixed(2) + "%20kWh%20of%20clean,%20renewable%20energy%20today!";
      var path_to_twitter = "http://www.twitter.com/intent/tweet?url="+url+"&text="+text+"&via=98Lumens"

      $('.twitter-update').append('<a href='+path_to_twitter+'><button class="btn btn-mini"><%= image_tag("icons/twitter.png", :size=>"15x15") %>Tweet daily stats</button></a>');

  }));
</script>

app/views/users/_graph.html.erb
<h1>Hello</h1>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= form_tag users_path, :method => :get, :remote => true do %>
  <p>
    <%= submit_tag "Test", :name => nil, :class => "btn" %>
  </p>
<% end %>

<div id='test'>
</div>


<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/sandbox.html.erb
<head><%= javascript_include_tag "user_script.js" %></head>
<%# user row %>

<div class = "dashboard">
  <div class = "row-fluid">

<%#
  Make everything but the header a partial and render that based on how many panels one has
  user.panels.each do |f|
  end 
%>

<%# dash-header %>

    <h1 style="text-align:left"><b>98Lumens solar panel dashboard</b></h1>
    <div class= "span2" id="user-pic">
      <p>
        <%= image_tag avatar_url(@user), :size =>"85x90"%>
      </p>
    </div>

    <div class="span3" id="user-name">
        <p class="lead" id="name-text">
          <div class="twitter-update"><h4 style="float:left;padding-right:10px;"><%= @user.name %></h4>
          </div>
        </p>
        <% if !@panel.energy_data.empty? %>
        <p style="font-size:16px;padding-top:5px;">
          Location of solar panel: <b><%= @location %></b>
          
          <%# To change solar panel (change to dropdown later).
              Need to have this post to sandbox action with index
              param. 
          %>
          <% if @user.panels.length >1 %>
            <%= form_tag({:controller => "users", :action=>"sandbox", :method=>"post"}, {:class=>'panel-form'}) do %> 
              <!--<div class="field">
                <label>Panel # :</label>
                <%= text_field_tag :index %>
              </div>-->
            <%= collection_select(:energy_data, :panel_id, @user.panels.all, :panel_num, :name, options={:prompt=>"Veiwing "+ @panel.name}, html_options={:class => 'panel-select', :onchange => ("$(this).parent('form').submit();")}) %>
              <div class="actions">
              </div>
            <% end %>
          <% end %>

          </ul>
        </p>
        <% end %>
    </div>

    <div id="map_canvas" style="float:left;width:33%;height:100px"></div>


    <% if !@user.panels.first.energy_data.empty? %>
    <div id="weather">
      <%= @location %>
      <%= @weather %>
    </div>
    <% end %>

    <% if @panel.energy_data.empty? %>
      <p style="font-size:16px">
        <%= link_to "Learn how you can go solar and activate this dashboard", consult_path, :class=>"btn btn-success btn-large dash-btn" %>
      </p>
    <% end %>

</div>

  <%# --------------- %>

  <%# render a partial %>

<% if !@panel.energy_data.empty? %>

  <%# does this pass the panel object? how do I access it on the other side? @panel? %>
  <%= render :partial => "dash_content", :locals => { :panel => @user.panels.where(:panel_num=>1) } %>

<% end %>

</div>

app/views/users/show.html.erb
<!-- user row -->

<div class = "dashboard">
<div class = "row-fluid">

    <div class= "span2" id="user-pic">
      <p>
        <%= image_tag avatar_url(@user), :size =>"85x90"%>
      </p>
    </div>

    <div class="span3" id="user-name">
        <p class="lead" id="name-text">
          <h4><%= @user.name %></h4>
        </p>
        <% if !@user.energy_data.empty? %>
        <p style="font-size:16px">
         <!-- Joined: <%= @user.created_at.month %>-<%= @user.created_at.day %>-<%= @user.created_at.year %>
          <br>-->
          Location of solar panel: <b><%= @location %></b>
        </p>
        <% end %>
    </div>

    <% if !@user.energy_data.empty? %>
    <div id="weather">
      <%= @location %>
      <%= @weather %>
    </div>
    <% end %>

    <% if @user.energy_data.empty? %>
      <p style="font-size:16px">
        <%= link_to "Learn how you can go solar and activate this dashboard", consult_path, :class=>"btn btn-success btn-large dash-btn" %>
      </p>
    <% end %>

</div>

<% if !@user.energy_data.empty? %>

  <!-- chart and highlight row -->
<div class="row-fluid">
        <div class="graph-title"><p class="lead">Clean energy produced by your solar panel (kWh)</p></div>
        <p>
          <div class="btn-group  pull-right" data-toggle="buttons-radio">
            <button type="button" class="btn" id="day">Today</button>
            <button type="button" class="btn" id="month" >Last 30 days</button>
            <button type="button" class="btn" id="year">This year</button>
          </div>
        </p>
        <p>
          <div id="year-graph" style="width:100%;height:400px;"></div>
        </p>
  </div>

  <div class="row-fluid highlight-boxes">
      <div class="highlight-box" id="sun-hl" title="kWh is the unit of measurement for electricity. Your panel is responsible for <%= number_to_human(@user.calculate_overall_power_for, :precision =>2, :units => {:unit => 'Wh', :thousand => 'kWh', :million => 'MWh'}) %> of renewable energy over the duration of its operation.">
        <div class='highlight-banner'>
          <div class="highlight"><%= number_to_human(@user.calculate_overall_power_for, :precision =>2, :units => {:unit => 'Wh', :thousand => 'kWh', :million => 'MWh'}) %></div>
          <div class="sub-highlight">Lifetime output</div>
        </div>
      </div>
      <div class="vertical-space"></div>
      <div class="highlight-box" id="dollar-hl" title="The clean energy produced by your panel is being sold to a local utility and has generated $<%= number_to_human(@user.calculate_overall_money_for, :precision => 2) %> for you.">
        <div class='highlight-banner'>
          <div class="highlight">$<%= number_to_human(@user.calculate_overall_money_for, :precision => 4) %></div>
          <div class="sub-highlight">Lifetime earning</div>
        </div>
      </div>
      <div class="vertical-space"></div>
      <div class="highlight-box" id="green-hl" title="The dirty energy replaced by your panel is equivalent to planting <%= number_to_human(@user.calculate_overall_trees_for, :precision => 0, :units => {:unit => 'tree', :ten => 'trees'}) %>.">
        <div class='highlight-banner'>
          <div class="highlight"><%= number_to_human(@user.calculate_overall_trees_for, :precision => 0, :units => {:unit => 'tree', :ten => 'trees'}) %></div>
          <div class="sub-highlight">Equivalent trees planted</div>
        </div>
      </div>

     <!--   <table id="sidebar-graph">
          <td id="sun-hl" rel="tooltip" title="kWh is the unit of measurement for electricity. Your panel is responsible for <%= number_to_human(@user.calculate_overall_power_for, :precision =>2, :units => {:unit => 'Wh', :thousand => 'kWh', :million => 'MWh'}) %> of renewable energy over the duration of its operation.">
            <h1><%= number_to_human(@user.calculate_overall_power_for, :precision =>2, :units => {:unit => 'Wh', :thousand => 'kWh', :million => 'MWh'}) %></h1></td>
          <td id="dollar-hl" rel="tooltip" title="The clean energy produced by your panel is being sold to a local utility and has generated $<%= number_to_human(@user.calculate_overall_money_for, :precision => 2) %> for you.">
            <h1>$<%= number_to_human(@user.calculate_overall_money_for, :precision => 4) %></h1></td>
          <td id="green-hl" rel="tooltip" title="The dirty energy replaced by your panel is equivalent to planting <%= number_to_human(@user.calculate_overall_trees_for, :precision => 0, :units => {:unit => 'tree', :ten => 'trees'}) %>.">
            <h1><%= number_to_human(@user.calculate_overall_trees_for, :precision => 0, :units => {:unit => 'tree', :ten => 'trees'}) %></h1></td>
          </tr>
        </table> -->
  </div>

<!-- Table for all metrics

      <div class="btn-group btn-group-vertical">
        <button class= "btn btn-block" id="perf">Performance</button>
        <button class= "btn btn-block" id="finance">Finance</button>
        <button class= "btn btn-block" id="green">Environment</button>
      </div>

<div class="row-fluid">
  <div class="span6 offset2">
    <p>
      <h2>Cumulative metrics</h2>
      <table class="table table-striped">
        <tr>
          <th>Clean energy produced</th>
          <td><%= number_with_precision(@user.calculate_overall_power_for, :precision =>2) %> Wh</td>
        </tr>
        <tr>
          <th>Money accrued</th>
          <td><%= number_with_precision(@user.calculate_overall_money_for, :precision =>2) %> dollars </td>
        </tr>
        <tr>
          <th>Equivalent emissions captured</th>
          <td><%= number_with_precision(@user.calculate_overall_emissions_for, :precision =>2) %> kg </td>
        </tr>
        <tr>
          <th>Equivalent trees planted</th>
          <td><%= number_with_precision(@user.calculate_overall_trees_for, :precision =>2) %> trees</td>
        </tr>
        <tr>
          <th>Equivalent cars taken off the road</th>
          <td><%= number_with_precision(@user.calculate_overall_cars_for, :precision =>2) %> cars</td>
        </tr>
      </table>
    </p>
-->

<!--    <p>
    	<% if @user.energy_data.any? %>
          <h2> Last 10 energy-producing hours </h2>
          <table class="table table-striped">
            <tr>
              <th>Day</th>
              <th>Solar output</th>
              <th>Emissions saved</th>
              <th>Fraction of a tree planted</th>
              <th>Money accrued</th>
            </tr>
                <%= render :partial => 'energy_data/energy_datum.html.erb', :collection => @energy_data, :as => :energy %>
          </table>
        <% end %>
    </p> -->
<% end %>

</div>


<% javascript_tag do %>
 
<% end %>

<script type="text/javascript">
$(document).ready($(function () {
                  //alert((new Date()).getTime());

    var exValue = 1;
    var sideGraphStat = $("#sidebar-graph");
    var sideGraphTD = $("#sample")

     var xyData = <%= @monthTotals.to_json %>;
     var chartLabel = "Solar output (Wh)";
     var weekXY = <%= @weekTotals.to_json %>;
     var dayXY = <%= @dayTotals.to_json %>;

     var placeholder = $("#year-graph");
     var data = xyData;
     var options = {
          //lines: {show:true},
          points: {show:false},
          bars: {show:true,
            align: "center",
            barWidth: 21*(24 * 60 * 60 * 1000),
            lineWidth:0,
            fillColor: "rgba(68, 177, 217, 0.75)"}, //#*day
          xaxis: {
            mode: "time",
            timeformat: "%b",
            monthNames: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
            tickLength:0,
          },
          grid: {hoverable:true, 
                clickable:true, 
                autohighlight:true},
          yaxis: {
            show:true,
            tickLength:0
          }
          //timeformat: "%H %p",
          //twelveHourClock: true}
        };

      var plot = $.plot(placeholder,[data], options);

      $('#sun-hl').tooltip();
      $('#dollar-hl').tooltip();
      $('#green-hl').tooltip();

      $('#day').click(function(){
        data = switchProf(0);
        options = {
          bars: {show:true,
            align: "center",
            barWidth: 0.03*(24 * 60 * 60 * 1000),
            lineWidth:0,
            fillColor: "rgba(68, 177, 217, 0.75)"},
          xaxis: {
            mode: "time",
            //timeformat: "%m"
            //timeformat: "%H %p",
            twelveHourClock: true,
            tickLength:0,
          },
          grid: {hoverable:true, 
                clickable:true, 
                autohighlight:true},
          yaxis: {
            show:true,
            tickLength:0
          }
        };

        doThis();
      });

      $('#month').click(function(){
        data = switchProf(1);
        //alert(data);
        options = {
          bars: {show:true,
            align: "center",
            barWidth: 0.8*(24 * 60 * 60 * 1000),
            lineWidth:0,
            fillColor: "rgba(68, 177, 217, 0.75)"},
          xaxis: {
            mode: "time",
            //timeformat: "%m"
            timeformat: "%b-%d",
            dayNames: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
            tickLength:0,
          //twelveHourClock: true}
            },
          grid: {hoverable:true, 
                clickable:true, 
                autohighlight:true
              },
          yaxis: {
            show:true,
            tickLength:0
          }
        };
        doThis();
      });

      $('#year').click(function(){
        data = switchProf(2);
        options = {
          bars: {show:true,
            align: "center",
            barWidth: 21*(24 * 60 * 60 * 1000),
            lineWidth:0,
            fillColor: "rgba(68, 177, 217, 0.75)"},
          xaxis: {
            mode: "time",
            timeformat: "%b",
            monthNames: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
            tickLength:0,
          //timeformat: "%H %p",
          //twelveHourClock: true}
          },
          grid: {hoverable:true, 
                  clickable:true, 
                  autohighlight:true},
          yaxis: {
            show:true,
            tickLength:0
          }
        };
        doThis();
      });


  function switchProf(timeGran) {
    var dataReturn = [];
      switch (timeGran) {
        case 0:    //day
          dataReturn = <%= @dayTotals.to_json %>
          break;
        case 1:    //month
          dataReturn = <%= @weekTotals.to_json %>
          break;
        case 2:    //year
          dataReturn = <%= @monthTotals.to_json %>
          break;
      }

    return dataReturn;
  }

//redraws canvas
  function doThis() {
     //placeholder.css("display","none");
     $.plot(placeholder,[data], options);
     //placeholder.fadeIn(200);
  } 

  //event listeners

      function showTooltip(x, y, contents) {
        $('<div id="tooltip">' + contents + '</div>').css( {
            position: 'absolute',
            display: 'none',
            top: y - 30,
            left: x + 5,
            border: '1px solid #fdd',
            padding: '2px',
            'background-color': '#fee',
            opacity: 0.80
        }).appendTo("body").fadeIn(200);
    }

    //var previousPoint = null;
      placeholder.bind("plothover", function (event, pos, item) {
         // alert('check');
       // if ($("#enableTooltip:checked").length > 0) {
            if (item) {
                if (previousPoint != item.dataIndex) {
                    previousPoint = item.dataIndex;
                    
                    $("#tooltip").remove();
                    var x = item.datapoint[0].toFixed(2),
                        y = item.datapoint[1].toFixed(2);
                    
                    showTooltip(item.pageX, item.pageY,
                                y + " kWh");
                }
            }
            else {
                $("#tooltip").remove();
                previousPoint = null;            
            }
        //}
    });

    placeholder.bind("plotclick", function(event, pos, item) {
      //alert('woo');
    })
    
    placeholder.resize(function () {
      /*  $("body").prepend("<div>Placeholder is now "
                           + $(this).width() + "x" + $(this).height()
                           + " pixels</div>"); */
    });
}));
</script>