config/routes.rb
A98lumens::Application.routes.draw do
  devise_for :users

  ActiveAdmin.routes(self)

  root :to => "static_pages#home"

  match 'sandbox', :to=> "users#sandbox", :as => "sandbox"
  match 'about', :to=> "static_pages#about", :as => "about"
  match 'contact', :to=> "static_pages#contact", :as => "contact"
  match 'projects', :to=> "static_pages#projects", :as => "projects"
  match 'get/state_retail_price', :to => "static_pages#state_retail_price", :as => "state_retail_price"
  match 'test', :to=> "static_pages#test", :as => "test"
  match 'learn', :to=> "static_pages#learn", :as => "learn"
  match 'faqs', :to=> "static_pages#faqs", :as => "faqs"
  match 'consult', :to=> "static_pages#consult", :as => "consult"
  match 'pricing', :to=> "static_pages#pricing", :as => "pricing"
  match 'reserve', :to=> "static_pages#reserve", :as => "reserve"
  match 'benefits', :to=> "static_pages#benefits", :as => "benefits"
  match 'submit_reserve', :to=> "static_pages#submit_reserve", :as => "submit_reserve"
  match 'info_mail', :to=> "static_pages#info_mail", :as => "info_mail"
  match 'calculator', :to=> "static_pages#calculator", :as => "calculator"
  match 'data/state_retail_price', :to => "static_pages#state_retail_price", :as => "state_retail_price"

  resources :energy_data

  resources :users

  match '/users/edit', :to => "devise/registrations#edit", :as => "edit_user_registration"
  match '/users/new', :to => "devise/registrations#new", :as => "new_user_registration"
  match 'get/user_data', :to => "users#user_inst_data", :as => "user_inst_data"

end

app/controllers/energy_data_controller.rb
class EnergyDataController < ApplicationController
  # GET /energy_data
  # GET /energy_data.json
  def index
    @energy_data = EnergyDatum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @energy_data }
    end
  end

  # GET /energy_data/1
  # GET /energy_data/1.json
  def show
    @energy_datum = EnergyDatum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @energy_datum }
    end
  end

  # GET /energy_data/new
  # GET /energy_data/new.json
  def new
    @energy_datum = EnergyDatum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @energy_datum }
    end
  end

  # GET /energy_data/1/edit
  def edit
    @energy_datum = EnergyDatum.find(params[:id])
  end

  # POST /energy_data
  # POST /energy_data.json
  def create
    @energy_datum = EnergyDatum.new(params[:energy_datum])

    respond_to do |format|
      if @energy_datum.save
        format.html { redirect_to @energy_datum, notice: 'Energy datum was successfully created.' }
        format.json { render json: @energy_datum, status: :created, location: @energy_datum }
      else
        format.html { render action: "new" }
        format.json { render json: @energy_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /energy_data/1
  # PUT /energy_data/1.json
  def update
    @energy_datum = EnergyDatum.find(params[:id])

    respond_to do |format|
      if @energy_datum.update_attributes(params[:energy_datum])
        format.html { redirect_to @energy_datum, notice: 'Energy datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @energy_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /energy_data/1
  # DELETE /energy_data/1.json
  def destroy
    @energy_datum = EnergyDatum.find(params[:id])
    @energy_datum.destroy

    respond_to do |format|
      format.html { redirect_to energy_data_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/energy_data_helper.rb
module EnergyDataHelper
end

app/views/energy_data/_energy_datum.html.erb
	<% if energy.power <= 0 %>
	<% else %>
		<tr>
			<td><%= energy.month %>/<%=energy.day %> at <%= energy.hour %>:00</td>
			<td><%= energy.power %> W</td>
			<td><%= number_with_precision(energy.calculate_emissions_for, :precision=>2) %> kg</td>
			<td><%= number_with_precision(energy.calculate_trees_for, :precision=>4) %> trees</td>
			<td><%= number_with_precision(energy.calculate_money_for, :precision=>4) %> cents</td>
		</tr>
	<% end %>

app/views/energy_data/_form.html.erb
<%= form_for(@energy_datum) do |f| %>
  <% if @energy_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@energy_datum.errors.count, "error") %> prohibited this energy_datum from being saved:</h2>

      <ul>
      <% @energy_datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :month %><br />
    <%= f.number_field :month %>
  </div>
  <div class="field">
    <%= f.label :day %><br />
    <%= f.number_field :day %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :hour %><br />
    <%= f.number_field :hour %>
  </div>
  <div class="field">
    <%= f.label :power %><br />
    <%= f.text_field :power %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/energy_data/_month_data.html.erb
<li>
  <span class="content">
 	Month total: <%= month %>
  </span>
</li>

app/views/energy_data/edit.html.erb
<h1>Editing energy_datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @energy_datum %> |
<%= link_to 'Back', energy_data_path %>

app/views/energy_data/index.html.erb
<h1>Listing energy_data</h1>

<table>
  <tr>
    <th>Month</th>
    <th>Day</th>
    <th>Year</th>
    <th>Hour</th>
    <th>Power</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @energy_data.each do |energy_datum| %>
  <tr>
    <td><%= energy_datum.month %></td>
    <td><%= energy_datum.day %></td>
    <td><%= energy_datum.year %></td>
    <td><%= energy_datum.hour %></td>
    <td><%= energy_datum.power %></td>
    <td><%= energy_datum.user_id %></td>
    <td><%= link_to 'Show', energy_datum %></td>
    <td><%= link_to 'Edit', edit_energy_datum_path(energy_datum) %></td>
    <td><%= link_to 'Destroy', energy_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Energy datum', new_energy_datum_path %>

app/views/energy_data/new.html.erb
<h1>New energy_datum</h1>

<%= render 'form' %>

<%= link_to 'Back', energy_data_path %>

app/views/energy_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Month:</b>
  <%= @energy_datum.month %>
</p>

<p>
  <b>Day:</b>
  <%= @energy_datum.day %>
</p>

<p>
  <b>Year:</b>
  <%= @energy_datum.year %>
</p>

<p>
  <b>Hour:</b>
  <%= @energy_datum.hour %>
</p>

<p>
  <b>Power:</b>
  <%= @energy_datum.power %>
</p>

<p>
  <b>User:</b>
  <%= @energy_datum.user_id %>
</p>


<%= link_to 'Edit', edit_energy_datum_path(@energy_datum) %> |
<%= link_to 'Back', energy_data_path %>