config/routes.rb
A98lumens::Application.routes.draw do
  devise_for :users

  ActiveAdmin.routes(self)

  root :to => "static_pages#home"

  match 'sandbox', :to=> "users#sandbox", :as => "sandbox"
  match 'about', :to=> "static_pages#about", :as => "about"
  match 'contact', :to=> "static_pages#contact", :as => "contact"
  match 'projects', :to=> "static_pages#projects", :as => "projects"
  match 'get/state_retail_price', :to => "static_pages#state_retail_price", :as => "state_retail_price"
  match 'test', :to=> "static_pages#test", :as => "test"
  match 'learn', :to=> "static_pages#learn", :as => "learn"
  match 'faqs', :to=> "static_pages#faqs", :as => "faqs"
  match 'consult', :to=> "static_pages#consult", :as => "consult"
  match 'pricing', :to=> "static_pages#pricing", :as => "pricing"
  match 'reserve', :to=> "static_pages#reserve", :as => "reserve"
  match 'benefits', :to=> "static_pages#benefits", :as => "benefits"
  match 'submit_reserve', :to=> "static_pages#submit_reserve", :as => "submit_reserve"
  match 'info_mail', :to=> "static_pages#info_mail", :as => "info_mail"
  match 'calculator', :to=> "static_pages#calculator", :as => "calculator"
  match 'data/state_retail_price', :to => "static_pages#state_retail_price", :as => "state_retail_price"

  resources :energy_data

  resources :users

  match '/users/edit', :to => "devise/registrations#edit", :as => "edit_user_registration"
  match '/users/new', :to => "devise/registrations#new", :as => "new_user_registration"
  match 'get/user_data', :to => "users#user_inst_data", :as => "user_inst_data"

end

app/views/layouts/_footer.html.erb
<!--<footer class="footer">
  <small>
    2012 Copyright 98Lumens
  </small>
  <nav>

  </nav>
</footer>-->

<section id="copyright" class="clearfix">
  <div class="container">
    <div class="row">
      <div class="span12">
        <p> © Copyright 98lumens inc.</p>
        
        <!--copyright menu starts-->
        <ul class="copyright-menu">
          <li><a href="#">Home</a></li>
          <li><a href="contact.html">Contact us</a></li>
          <li><a href="#">Privacy Policy</a></li>
          <li><a href="#">Terms & Conditions</a></li>
          <li><a href="#">Site Map</a></li>
          <li><a href="#">News</a></li>
        </ul>
        <!--copyright menu ends--> 
        
      </div>
    </div>
  </div>
</section>

app/views/layouts/_header.html.erb
<!--<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
  	<div class="container">
  		<div id="nav-items">
  			<%= render 'devise/menu/registration_items' %>
  			<%= render 'devise/menu/login_items' %>
 	 	</div>	
    </div>
  </div>
</header>-->

  <div class="container">
    <div class="row"> 
      
      <!--logo starts-->
      <div class="span4 logo"><a href=<%= root_path %>><%= image_tag("98lumens logo.png", :size=>"148x80") %></a></div>
      <!--logo ends-->
      
      <div class="span8 clearfix"> 
        
        
        <!--menu starts-->
        <div id="smoothmenu" class="ddsmoothmenu">
          <ul>
            <li><%=link_to "Home", '#' %></li>
            <li><%=link_to "Learn", '#' %></a>
              <ul>
                <li><a href="">98lumens Solar Process</a></li>
                <li><%=link_to "FAQs", '#' %></li>
              </ul>
            </li>
            <li><%=link_to "Benefits", '#' %></li>
 			<li><%=link_to "About", about_path %> </li>
            <li><%= link_to "Contact", '#' %></li>
            <% if signed_in? %>
                <div class="dropdown pull-right btn">
                  <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="/page.html">
                    <b>Account</b>
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                    <%= link_to("Dashboard", user_path(current_user)) %>
                    <%= link_to("Logout", destroy_user_session_path, :method => :delete) %>
                  </ul>
              </div>
            	
            <% else %>
            	<li><%= link_to("Sign in", new_user_session_path) %></li>
            <% end %>
          

          </ul>

        </div>
        <!--menu ends--> 
        
      </div>
    </div>
  </div>


<script type="text/javascript">
  $('.dropdown-toggle').dropdown()
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>98lumens - Solar power for everyone!</title>
  <%= include_gon %>
  <%= javascript_include_tag "jquery-1.8.1.js" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "flot/jquery.flot.js" %>
  <%= javascript_include_tag "rails.js" %>
  <%= javascript_include_tag "flot-test.js" %>
  <%= javascript_include_tag "updateHTML.js" %>
  <%= javascript_include_tag "flot/jquery.flot.time.js" %>
  <%= javascript_include_tag "flot/jquery.flot.resize.js" %>
  <%= javascript_include_tag "flot/jquery.flot.stack.js" %>
  <%= javascript_include_tag "jquery.elastislide.js" %>
  <%= javascript_include_tag "jquery.flexslider-min.js" %>
  <%= javascript_include_tag "jquery.prettyPhoto.js" %>
  <%= javascript_include_tag "show_helpers.js" %>
  <%= javascript_include_tag "NumberFormat154.js" %>
  <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-tooltip.js"></script>
  <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
  <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-collapse.js"></script>
  <script src="http://jquery-numberformatter.googlecode.com/svn/trunk/src/jquery.numberformatter.js"></script>
  <script type='text/javascript' src='https://www.google.com/jsapi'></script>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDLpJ6v0QXHX-8bYykOJ-yJb67wDIgX-7o&sensor=false"></script>
  <script type="text/javascript">
      google.load('visualization', '1', {packages: ['gauge']});
  </script>
  <!--Fav and touch icons-->
  <link rel="shortcut icon" href="icons/favicon.ico">
  <link rel="apple-touch-icon" href="icons/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="icons/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="icons/apple-touch-icon-114x114.png">
  <link rel="icon" href="http://www.98lumens.com/favicon.ico" type="icons/favicon.ico">
</head>
<body>
  <section id="header">
    <%= render 'layouts/header' %>
  </section>
  <section id="content">
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
          </div>
        <br>
      <%= render 'layouts/footer' %>
  </section>
    <script type="text/javascript">
      <% if alert.nil? %>
        $(".alert").hide()
      <% else %>
        $(".alert").show()
      <% end %>
    </script>
</body>
</html>

app/views/layouts/override.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>98lumens - Solar power for everyone!</title>
  <%= javascript_include_tag "jquery-1.8.1.js" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "flot/jquery.flot.js" %>
  <%= javascript_include_tag "rails.js" %>
  <%= javascript_include_tag "flot-test.js" %>
  <%= javascript_include_tag "updateHTML.js" %>
  <%= javascript_include_tag "flot/jquery.flot.time.js" %>
  <%= javascript_include_tag "flot/jquery.flot.resize.js" %>
  <%= javascript_include_tag "flot/jquery.flot.stack.js" %>
  <%= javascript_include_tag "jquery.elastislide.js" %>
  <%= javascript_include_tag "jquery.flexslider-min.js" %>
  <%= javascript_include_tag "jquery.prettyPhoto.js" %>
  <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-tooltip.js"></script>
  <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
  <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-collapse.js"></script>
  <!--Fav and touch icons-->
  <link rel="shortcut icon" href="icons/favicon.ico">
  <link rel="apple-touch-icon" href="icons/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="icons/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="icons/apple-touch-icon-114x114.png">
  <link rel="icon" href="http://www.98lumens.com/favicon.ico" type="icons/favicon.ico">
</head>
<body>
  <section id="header">
    <%= render 'layouts/header' %>
  </section>
  <section id="content">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
          
      <%= render 'layouts/footer' %>
  </section>
    <script type="text/javascript">
      <% if alert.nil? %>
        $(".alert").hide()
      <% else %>
        $(".alert").show()
      <% end %>
    </script>
</body>
</html>